project_name: c8y

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "Cumulocity CLI {{.Version}}"

before:
  hooks:
    - go mod tidy
    - make generate_go_code 
    - make manpages

builds:
  - <<: &build_defaults
      binary: bin/c8y
      main: ./cmd/c8y/main.go
      ldflags:
        - -s -w -X github.com/reubenmiller/go-c8y-cli/pkg/cmd.buildVersion={{.Version}} -X github.com/reubenmiller/go-c8y-cli/pkg/cmd.buildBranch={{.Branch}}
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/c8y*.1
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: GitHub
    homepage: https://reubenmiller.github.io/go-c8y-cli/
    bindir: /usr/bin
    description: Cumulocity's unoffical command line tool.
    formats:
      - deb
      - rpm
      - apk
    # Packages your package suggests installing.
    suggests:
      - jq
      - git

    # create empty folder for the user to add their own templates and views
    empty_folders:
      - /opt/c8y/templates/custom
      - /opt/c8y/views/custom

    contents:
      - src: "./share/man/man1/c8y*.1"
        dst: "/usr/share/man/man1"

      - src: "./tools/shell/c8y.plugin.*"
        dst: /opt/c8y/plugins/
      
      - src: ./examples/views/default/*.json
        dst: /opt/c8y/views/default/

      - src: ./examples/templates/test/test*.jsonnet
        dst: /opt/c8y/templates/test/
      
      - src: ./examples/settings.json
        dst: /opt/c8y/settings.json
