#---------------------------------#
#      general configuration      #
#---------------------------------#
skip_commits:
   files:
     - docs/*
     - '**/*.md'
     - test/*.go

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  # Deploy timeout
  TimeOutMins: 2

  # AppVeyor Apikey used when checking status of build
  ApiKey:
    secure: JWEJSOBJbCfIMb+J4Cnb2Fbn7gVsWfqWsdQEoqLvN5c=

  # nuget api key used to publish to PowerShell Gallery
  nuget_apikey:
    secure: rfFg7q0kl5loV6mXquG73NKa5NEAtLKyKHhQJy0TiwIXdeMHYhqGqZCl5sb/7Hpz

  C8Y_HOST:
    secure: 1mpbPj8TYp5TrBamoABxWATQWb1t1BIsdyos8N8R60QOVB1puaWvH/yuw+0ClWjk
  C8Y_TENANT:
    secure: dldySxQAn1jXmUCoZFkKRw==
  C8Y_USER:
    secure: 7nnf6/dt+mNSq5pVZrdXBw==
  C8Y_PASSWORD:
    secure: olAYnZxd7FOGGVMy0pgrTcl+LcNGEtraxIkPJftUndk=
  # Max timeout for each request (in milliseconds)
  C8Y_TIMEOUT: 30000
image:
  - Visual Studio 2019
  - Ubuntu
  - macos

install:
- ps: ./scripts/build-powershell/install.ps1

build_script:
- ps: ./scripts/build-powershell/build.ps1

test_script:
- ps: ./scripts/build-powershell/test.ci.ps1


artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: tools/PSc8y/Dependencies/c8y*


deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    release: c8y-v$(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: oFVzQ+7hf85G71CNiQaUl5yUeqHdQHKkf14jaXSociwIEPWS9BWU9y3TQRlk7Pg8
    artifact: /c8y.*/           # upload all NuGet packages to release assets
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only

for:
  # Only publish on the last build
  -
    matrix:
      only:
        - image: macos

    on_success:
      # publish to Powershell Gallery
    - ps: ./scripts/build-powershell/publish.ps1
