name: release

on:
  push:
    branches:
      - "master"
      - "main"
      - "next"
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Generate changelog
        run: |
          echo "GORELEASER_CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          git fetch --unshallow
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-nuget:
    runs-on: ubuntu-18.04
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@v2

    - name: Build Powershell Module
      run: make build_powershell

    - uses: actions/upload-artifact@v2
      with:
        name: ReleaseArtifacts
        path: |
          tools/PSc8y/dist/PSc8y.zip
          tools/PSc8y/Dependencies/*

    - name: Publish Powershell Module (PSc8y)
      run: make publish

  publish-docker-latest:
    runs-on: ubuntu-latest
    needs: [publish-nuget]
    if: "true"
    env:
      CR_PAT: ${{ secrets.CR_PAT }}

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: publish docker images
      run: make VERSION=${GITHUB_REF} publish-docker
